develop:
  port: 8040
  log:
    pathLogReq: "D:\\var\\log\\reqInfo"
    pathLogRes: "D:\\var\\log\\resInfo"

staing:
  port: 8040
  log:
    pathLogReq: "/app/suggestfund/log/info"
    pathLogRes: "/app/suggestfund/logRes/info"
